config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  get 'home/index'
  # resources :categories do
  #   resources :tasks
  # end

  resources :projects, shallow: true do
    resources :categories do
      resources :tasks
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence:true, length: { maximum: 35 }
  belongs_to :project 
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence:true, length: { maximum: 40 }

  has_many :categories, dependent: :destroy
  belongs_to :user 
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence:true, length: { maximum: 100 }

  validates :priority_level, presence:true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 4 }

  belongs_to :category
  belongs_to :user

  scope :priority, -> { where("completed = false and due_date <= '#{Date.today}'") }


  PRIORITY_OPTIONS = [    
    [' ', '4'],
		['Urgent', '1'],
		['Medium', '2'],
		['Low', '3']
  ]

  def priority_color
    case priority_level
    when 1
      'red'
    when 2
      'yellow'
    when 3
      'gray'
    when 4
      'hidden'
    end
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: { case_sensitive: false }

  validates :first_name, presence: true

  validates :last_name, presence: true

  has_many :projects, dependent: :destroy 
  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_project, only: [:index, :new, :create]
  before_action :set_category_user, only: [:edit, :update, :destroy]
  before_action :owns_category?, only: [:edit, :update, :destroy]
  # def index
  #   @categories = @project.categories
  # end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)
    @category.user_id = current_user.id
    @category.project_id = @project.id
    if @category.save
      redirect_to project_path @project
    else
      render :new
    end
  end

  def edit
    @category = current_user.categories.find(set_category)
  end

  def update
    @category = current_user.categories.find(set_category)
    if @category.update(category_params)
      redirect_to project_path(@category.project_id)
    else 
      render :edit
    end
  end

  def destroy
    @category = current_user.categories.find(set_category)
    @category.destroy
    redirect_to project_path(@category.project_id)
  end

  private
  def get_project
    @project = current_user.projects.find(params[:project_id])
  end
  
  def set_category
    params[:id]
  end

  def category_params
    params.require(:category).permit(:title, :project_id, :user_id)
  end

  def set_category_user
    @category = Category.find(params[:id])
  end
  
  def owns_category?
    redirect_to projects_path unless current_user.id == @category.user_id 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in? 
      @projects = current_user.projects
      @tasks = current_user.tasks

      @priority_tasks = Task.priority.where(user_id: current_user.id)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project_user, only: [:show, :edit, :update, :destroy]
  before_action :user_is_owner?, only: [:show, :edit, :update, :destroy]


  def index
    @projects = current_user.projects
  end

  def new
    @project = current_user.projects.build
    @projects = current_user.projects
  end

  def show
    @project = current_user.projects.find(set_project)
  end

  def create
    @project = current_user.projects.build(project_params)
    @projects = current_user.projects   
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
    @project = current_user.projects.find(set_project)
  end

  def update
    @project = current_user.projects.find(set_project)
    if @project.update(project_params)
      redirect_to project_path(@project)
    else 
      render :edit
    end
  end

  def destroy
    @project = current_user.projects.find(set_project)
    @project.destroy
    redirect_to projects_path
  end

  private

  def set_project
    params[:id]
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project_user
    @project = Project.find(params[:id])
  end
  
  def user_is_owner?
    redirect_to projects_path unless current_user.id == @project.user_id 
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_category, only: [:index, :new, :create]
  before_action :set_task_user, only: [:edit, :update, :destroy]
  before_action :owns_task?, only: [:edit, :update, :destroy]

  def new 
    @task = current_user.tasks.build 
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.user_id = current_user.id
    @task.category_id = @category.id
    @task.project_id = @category.project_id
    if @task.save 
	    redirect_to project_path(@task.project_id)
    else 
      render :new
    end
  end

  def edit
    @task = current_user.tasks.find(set_project)
  end

  def update
    @task = current_user.tasks.find(set_project)
    if @task.update(task_params)
      redirect_to project_path(@task.project_id)
    else 
      render :edit
    end
  end

  def destroy
    @task = current_user.tasks.find(set_project)
    @task.destroy
    redirect_to project_path(@task.project_id)
  end

  private
  def set_project
    params[:id]
  end

  def get_category
    @category = Category.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:name, :category_id, :description, :priority_level, :due_date, :user_id, :project_id, :completed)
  end

  def set_task_user
    @task = Task.find(params[:id])
  end
  
  def owns_task?
    redirect_to projects_path unless current_user.id == @task.user_id 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
	<% if @category.errors.any?%>
		<div class="alert alert-error alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<strong>Whoops!</strong> <%= @category.errors.full_messages.to_sentence %>
		</div>
	<% end%>


	<div class="container mt-5">
		<div class="form-layout-center account-form mt-5 task--card">
			<h4 class="text-center mb-4 mt-2 purple-text" style="color:gray">Edit category</h4>
			<%= form_for @category, url:category_path(@category) do |f| %>
			<div class="form-floating float-pass-2 mb-3 mt-3">
				<%= f.text_field :title, autofocus: true, class: "form-control", id: "floatingInput", placeholder: "Sample Category" %>
				<%= f.label "Category Title", for: "floatingInput" %>
			</div>

			<div class="actions text-center mb-5">
				<%= f.submit "Update Category", class:"btn btn-custom-primary", style:"width:100%" %>
			</div>
			<% end %>

		</div>
	</div>

app/views/categories/index.html.erb
<h1> INDEX CATEGORIES </h1>

<div class="container mt-1 p-5">
  <table class="table table-light table-striped table-bordered table-hover" style="overflow-x:auto;">
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td> <%=category.id%></td>
        <td> <%=category.title%></td>
        <td> <%= link_to "View", project_categories_path(category)%> </td>
        <td> <%= link_to "Edit", edit_category_path(category)%> </td> 
        <td> <%= link_to "Delete", category_path(category), :method => :Delete, data: {confirm: "Are you sure you want to delete this?"} %></td>
        <td> <%= link_to "View Tasks", category_tasks_path(category)%> </td>
        <td> <%= link_to "New Task", new_category_task_path(category)%> </td>
      </tr>
        <% category.tasks.each do |task| %>
          <tr>
            <td> <%=task.id%></td>
            <td> <%=task.name%></td>
            <td> <%=task.description%></td>
            <td> <%=task.priority_level%></td>
            <td> <%=task.due_date%></td>

            <td> <%= link_to "View", category_tasks_path(task)%> </td>
            <td> <%= link_to "Edit", edit_task_path(task)%> </td> 
            <td> <%= link_to "Delete", task_path(task), :method => :Delete, data: {confirm: "Are you sure you want to delete this?"} %></td>
          </tr>
        <% end %>

      <%# </tr> %>
      <% end %>
    </tbody>
  </table>
  <br/>
  <%= link_to "Back to Home", root_path, class:"btn btn-secondary"%>
  <%= link_to "Back to Projects", projects_path, class:"btn btn-secondary"%>
  <%= link_to "New Category for this project", new_project_category_path, class:"btn btn-secondary"%>


</div>

app/views/categories/new.html.erb
	<% if @category.errors.any?%>
		<div class="alert alert-error alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<strong>Whoops!</strong> <%= @category.errors.full_messages.to_sentence %>
		</div>
	<% end%>
		
  <div class="container mt-5">
    <div class="form-layout-center account-form mt-5 task--card">
      <h4 class="text-center mb-4 mt-2 purple-text" style="color:gray">Create a new category</h4>
      <%= form_with scope:@category, url: project_categories_path , local:true do |f| %>
      <div class="form-floating float-pass-2 mb-3 mt-3">
        <%= f.text_field :title, autofocus: true, class: "form-control", id: "floatingInput", placeholder: "Sample Category" %>
        <%= f.label "Category Title", for: "floatingInput" %>
      </div>

      <div class="actions text-center mb-5">
        <%= f.submit "Submit", class:"btn btn-custom-primary", style:"width:100%" %>
      </div>
      <% end %>

    </div>
  </div>

app/views/home/_priority-tasks.html.erb
  <details open class="category--card p-2">
    <summary> <span class="summary-header"> Priorities for today: <b><%= Time.now.strftime("%B %d") %> </b> </span> </summary>
    <table class="table">
      <thead>
        <tr> 
          <th class="gray-text text-center col-md-1"><small>Priority</small> </th>
          <th class="gray-text text-center col-md-3"><small>Due <span class="due">Date</span></small></th>
          <th class="gray-text text-center col-md-6"><small>Task</small> </th>
          <th class="gray-text text-center col-md-2 "></th>
        </small> </tr>
      </thead>
      <tbody>
        <% @priority_tasks.order("priority_level ASC").each do |task| %>
        <tr class="task-table">
          <td class="text-center task-text"> <span class="home-prio-badge badge-<%= task.priority_color %>"></span> </td>
          <td class="task-text text-center"><small> <i class="fa fa-calendar">&nbsp;</i><%= task.due_date.try(:strftime, ("%b. %d, '%y"))%> </small></div> </td>
          <td class="task-text">
            <small class="edit-task-link"> <%= link_to fa_icon("edit"), edit_task_path(task),  class:"edit-task-link small-icon"%> </small>
            <%=task.name %> 
          </td>
          <td class="task-text"> <small><%= link_to "Project >", project_path(task.project_id), class:"prio-badge" %></small></td>
        </tr>
        <% end %> 
      </tbody>
    </table>
  </details>

app/views/home/_projects.html.erb
<% @projects.order("updated_at ASC").last(3).each do |project| %>
  <a href="<%= project_path(project) %>" class="project--card"> 
    <div>
      <div class="p-2 mt-3 mx-2 project--column">
        <h3 class="p-0 text-center"> <%= project.name %> </h3>
        <div class="hover--only text-center">
          <h4> <%= project.name %> </h4>
          <hr>
          <p class="text-truncate"> <%=project.description%> </p>
        </div>
      </div>
    </div>
  </a>
<% end %>
<a href="<%= new_project_path %>" class="light--card m-2 p-3"> 
  <h3 class="p-2 text-center mt-3"> + New project </h3>
</a>

app/views/home/index.html.erb
<% if user_signed_in? %>

  <div class="container mt-5 d-flex flex-row home">
    <div class="col-md-5 mr-custom">
      <% if @projects.length < 2 %>
        <div class="mt-4 mb-2 p-3"> </div>
      <% end %>
        <% if @priority_tasks.any?%>
          <%= render 'home/priority-tasks' %>
        <% else %>
          <%= image_tag("home-bg-2.png", class:"", width:"90%") %>
          <h3 class="text-center"> No tasks due today! :) </h3>
        <% end %> 
    </div>

    <div class="col-md-6">
      <div class="d-flex flex-column">
        <% if @projects.length < 2 %>
          <div class="mt-5 mb-3"> </div>
        <% end %>
        <div class="d-flex flex-row category--card mb-3 mx-custom">
          <%= image_tag("bg-right-2.png", class:"", width:"30%") %>
          <div class="mt-5 mr-custom">
            <h3> Hello <%= current_user.first_name%>! </h3>
            <% if @priority_tasks.length == 1%>
              You have <%= @priority_tasks.length %> task due today!
            <% elsif @priority_tasks.length > 1 %>
              You have <%= @priority_tasks.length %> tasks due today!
            <% else %>
              Good job! You don't have any pending tasks for today!
            <% end %>
          </div>
        </div>
        <div class="d-flex flex-row flex-wrap mb-3">
          <%= render 'home/projects'%>
        </div>
        <% if @projects.any?%>
          <h4><%= link_to "View all projects > ", projects_path, class:"btn btn-primary mb-3 mx-3 float-right" %> </h4>
        <% end %>
      </div>
    </div>
  </div>

<% else %>
  <div class="container">
    <div class="d-flex flex-row justify-content-between mx-5 mt-5 header-div">
      <div class="header col-md-5">
        <h1 class="header-text">Easily manage your projects with <u class="workday">Workday</u></h1> 
        <p class="header-description">We help you organize your projects and allow you to focus on the work that needs to be done</p>
        <%= link_to "TRY IT FOR FREE", new_user_registration_path, class:"btn btn-custom-primary header-btn mt-3" %>
      </div>
      <div class="col-md-5 img-header">
        <%= image_tag("home-bg-1.png", class:"home-img-1") %>
        <%= image_tag("home-bg-3.png", class:"home-img-2") %>
        <div class="shape">
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_bg-images-edit.html.erb
<%= image_tag("bg-left-2.png", class:"bg-img-edit") %>
<%= image_tag("bg-right-2.png", class:"bg-img-left-edit") %>

app/views/layouts/_bg-images.html.erb
<%= image_tag("bg-left-2.png", class:"bg-img") %>
<%= image_tag("bg-right-2.png", class:"bg-img-right") %>

app/views/layouts/_header.html.erb
<header id="header"> 
  <nav id="nav-bar">
    <div class="logo"><%= link_to "Workday", root_path, class:"header-link" %></a></div>
  <!-- MENU TOGGLER -->
    <input type="checkbox" class="toggle-menu"> 
    <div class="hamburger">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
    </div>
    <ul class="navigation">
        <!-- Nav Item 1 -->
      <% if user_signed_in? %>
        <%# <div class="d-flex flex-row flex-nowrap"> %>
          <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/projects">Projects</a>
          </li>
        <%# </div> %>
      <% end %>
    <%# </ul>  %>
    <%# <div class="float-right my-2 my-lg-0"> %>
      <% if user_signed_in?%>
        <%# <div class="d-flex flex-row flex-nowrap"> %>
          <li class="nav-item"> <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-outline-secondary mx-2" %> </li>
          <li class="nav-item"> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-custom-primary mx-2" %> </li>
        <%# </div> %>
      <% else %>
        <%# <div class="d-flex flex-row flex-nowrap"> %>
          <li class="nav-item"> <%= link_to "Log In", new_user_session_path, class:"btn btn-outline-secondary mx-2" %> </li>
          <li class="nav-item"> <%= link_to "Get Started", new_user_registration_path, class:"btn  btn-custom-primary mx-2" %> </li>
        <%# </div> %>
      <% end %>
    </ul>
  </nav>
</header>

app/views/projects/_alert.html.erb
		<div class="alert alert-error alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<strong>Whoops!</strong> <%= @project.errors.full_messages.to_sentence %>
		</div>

app/views/projects/index.html.erb
<div class="container mt-5">
  <h1 class="mb-3 mx-3"> <%= current_user.first_name%>'s Projects </h1>
  <div class="d-flex flex-row flex-wrap mb-5 justify-con">
    <% @projects.each do |project| %>
      <a href="<%= project_path(project) %>" class="project--card"> 
        <div>
          <div class="p-2 mt-3 mx-2 project--column">
              <h3 class="p-0 text-center"> <%= project.name %> </h3>
            <div class="hover--only text-center">
              <h4> <%= project.name %> </h4>
              <hr>
              <p class="text-truncate"> <%=project.description%> </p>
            </div>
          </div>
        </div>
      </a>
    <% end %>
    <a href="<%= new_project_path %>" class="light--card"> 
      <h3 class="p-2 text-center mt-3"> + New project </h3>
    </a>
  </div>
  <%= link_to "Back", root_path, class:"btn btn-secondary"%>
    <%= link_to "New Project", new_project_path, class:"btn btn-secondary"%>
</div>

app/views/projects/show.html.erb
<div class="container mt-3">
  <%= link_to "< Back to Projects", projects_path, class:"no-line gray-text" %>

  <div class="d-flex justify-content-between align-items-end mt-2 margin-right-5">
    <div  class="" >
      <h1 class="p-0"> <%= @project.name %> </h1>
      <h5 class="mb-0"> <%= @project.description %> </h5>
    </div>
    <div class="text-end align-bottom" style="text-align: right">
        <div class="d-flex flex-nowrap justify-content-between proj-icons">
          <%#= link_to "Edit Project", edit_project_path(@project), class:"purple-text" %>
          <%#= link_to fa_icon("trash"), project_path(@project), :method => :Delete, data: {confirm: "Are you sure you want to delete this?"}, class:"red-icon" %>
        </div>
      <small class="text-end align-bottom ">Created: <%= @project.created_at.strftime('%b. %e, %Y')%> </small> <br/>
      <small class="text-end align-bottom">Last updated: <%= time_ago_in_words(@project.updated_at)%> ago</small> 
    </div>
  </div>
  <div class="mt-2">
    <%= link_to "Edit Project", edit_project_path(@project), class:"purple-text btn small-custom-btn" %>
    <%= link_to "+ Create new category", new_project_category_path(@project), class:"purple-text btn small-custom-btn mx-2" %>
    <%= link_to "Delete Project", project_path(@project), :method => :Delete, data: {confirm: "Are you sure you want to delete this? Note that all the tasks and categories of this project will be deleted as well"}, class:"red-icon btn small-custom-btn red-custom-btn" %>
  </div>
</div>

  <hr/>

<div class="category--container" id="category--container">
  <div class="d-flex flex-row overflow-auto mb-5 ml-5">
    <% @project.categories.each do |category| %>
      <div class="category--card custom-width m-1 mb-5">
        <div class="p-2 column">
          <div  class="mt-1 d-flex flex-row justify-content-between" >
            <h5 class="pad-title purple-text"><%= category.title%> </h5>
            <div class="col-md-2 d-flex justify-content-between mx-3">
              <small class="blue-text"><%= link_to fa_icon("edit"), edit_category_path(category)%></small> 
              <small> <%= link_to fa_icon("trash"), category_path(category), :method => :Delete, data: {confirm: "Are you sure you want to delete this?"}, class:'red-icon' %> </small>
            </div>
          </div>
          <div>
            <% category.tasks.each do |task| %>
            <div class="task--card">
              <div class="d-flex flex-column">
                <% if task.priority_level and !task.completed %>
                  <div  class="d-flex flex-row justify-content-between">
                    <span class="prio-badge badge-<%= task.priority_color %> mb-3 mt-1"></span>
                    <div class="fa--icon col-md-4 d-flex justify-content-between">
                      <small class="edit-task-link"> <%= link_to "Edit Task", edit_task_path(task),  class:"edit-task-link small-icon"%> </small>
                      <small> <%= link_to fa_icon("times"), task_path(task), :method => :Delete, data: {confirm: "Are you sure you want to delete this?"},  class:"red-icon small-icon pad-right" %> </small>
                    </div>
                  </div>
                <% elsif task.completed %>
                  <div  class="d-flex flex-row justify-content-between">  
                    <div class="mt-1 col-md-5 d-flex flex-row fa--icon prio-badge  ">
                      <i class="fa fa-check m-custom"></i>completed
                    </div>
                      <div class="fa--icon col-md-4 d-flex justify-content-between">
                      <small class="edit-task-link"> <%= link_to "Edit Task", edit_task_path(task),  class:"edit-task-link small-icon"%> </small>
                      <small> <%= link_to fa_icon("times"), task_path(task), :method => :Delete, data: {confirm: "Are you sure you want to delete this?"},  class:"red-icon small-icon pad-right" %> </small>
                    </div>
                  </div>
                <% else %>
                    <div  class="mt-1 d-flex flex-row justify-content-end" >
                      <div class="fa--icon col-md-4 d-flex justify-content-between">
                        <small class="edit-task-link"> <%= link_to "Edit Task", edit_task_path(task),  class:"edit-task-link small-icon"%> </small>
                        <small> <%= link_to fa_icon("times"), task_path(task), :method => :Delete, data: {confirm: "Are you sure you want to delete this?"},  class:"red-icon small-icon pad-right" %> </small>
                      </div>
                    </div>
                <% end %>

                <div  class="mt-1 d-flex flex-row justify-content-between" >
                  <p class="pad-title"><%= task.name%> </p>
                </div>
                <% if !task.completed and task.due_date%>
                    <div  class="d-flex flex-row justify-content-between" >
                      <div class="gray-text pad-title"><small> <i class="fa fa-calendar">&nbsp;</i><%= task.due_date.try(:strftime, ("%b. %d, '%y"))%> </small></div>
                    </div>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
          <div>
          <a href="<%= new_category_task_path(category) %>" class="no-line"> 
            <p class="text-center mb-0 p-2 no-line blue-text create--task"><b> + Create new task </b></p>
          </a>
          </div>
        </div>
      </div>
    <% end %>
          <a href="<%= new_project_category_path(@project) %>" class="no-line category--card mt-1 m-2 p-3 light--category"> 
            <p class="text-center mb-0 p-2 no-line purple-text"><b> + Create new category </b></p>
          </a>
  </div>
</div>

app/views/tasks/_alert.html.erb
	<% if @task.errors.any?%>
		<div class="alert alert-error alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<strong>Whoops!</strong> <%= @task.errors.full_messages.to_sentence %>
		</div>
	<% end%>

app/views/tasks/index.html.erb
<h1> INDEX TASKS </h1>

<div class="container mt-1 p-5">
  <table class="table table-light table-striped table-bordered table-hover" style="overflow-x:auto;">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Priority Level</th>
        <th>Due Date</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
      <tr>
        <td> <%=task.id%></td>
        <td> <%=task.name%></td>
        <td> <%=task.description%></td>
        <td> <%=task.priority_level%></td>
        <td> <%=task.due_date%></td>

        <td> <%= link_to "View", category_tasks_path(task)%> </td>
        <td> <%= link_to "Edit", edit_task_path(task)%> </td> 
        <td> <%= link_to "Delete", task_path(task), :method => :Delete, data: {confirm: "Are you sure you want to delete this?"} %></td>
      </tr>
    </tbody>
  </table>
  <br/>
  <%= link_to "Back to Home", root_path, class:"btn btn-secondary"%>
  <%= link_to "Back to Projects", projects_path, class:"btn btn-secondary"%>
  <%= link_to "Back to this Project", project_categories_path(task.project_id), class:"btn btn-secondary"%>
  <%= link_to "New Task for this Category", new_category_task_path, class:"btn btn-secondary"%>

  <% end %>

</div>

app/views/tasks/new.html.erb
	<% if @task.errors.any?%>
		<%= render 'tasks/alert'%>
	<% end%>
	<div class="container mt-5">
		<div class="form-layout-center account-form mt-5 task--card">
			<h4 class="text-center mb-4 mt-2" style="color:gray">Create a new task</h4>
      <%= form_with scope:@task, url: category_tasks_path , local:true do |f| %>

			<div class="form-floating float-pass-2 mb-3 mt-3">
				<%= f.text_field :name, autofocus: true, class: "form-control", id: "floatingInput", placeholder: "Sample Task" %>
				<%= f.label "Task Name", for: "floatingInput" %>
			</div>

			<div class="d-flex flex-row justify-content-between task-flex">
				<div class="label-task black-text mb-3 mt-1 col-md-4">
					<%= f.label "Priority Level", for: "dropdown" %> <br>
					<%= f.select :priority_level, Task::PRIORITY_OPTIONS, id: "dropdown",class: "form-control" %>
				</div>

				<div class="label-task black-text mb-3 mt-1">
					<%= f.label "Due date", for: "due-date" %>
					<%= f.date_field :due_date, class: "form-control", id: "due-date" %>
				</div>
			</div>

			<div class="mb-1 form-check form-text text-center">
				<%= f.check_box :completed, class:"form-text", id:"task-completed"  %>
				<%= f.label "Mark task as completed", for:"task-completed", class:"label-task black-text" %>
			</div>

			<div class="actions text-center mt-3 mb-3">
				<%= f.submit "Create Task", class:"btn btn-custom-primary", style:"width:100%" %>
			</div>
			<% end %>

		</div>
	</div>